### ISSUE TITLE
Uploading topology not working

### ISSUE THREAD

**Issue by jhahkala** [fiware-cybercaptor/cybercaptor-client#25]
I have the cybercapture-server running and can connect to it inside the machine using the commands as given in the documentation. And I have cybercapture-client running in the same machine and that seems to work too, I can connect to it with browser and upload topology. But after uploading the topology the other tabs appear, but all the screens have just blank views, like there would be no topology. I tried with the example topology dataSet.xml in the doc directory and with my own topology created by the cybercaptor-data-extraction. There were no errors on the browser nor in the log files.

Any idea how to debug/fix/find out what goes wrong?

**Comment by fxaguessy** [comment]
Sorry for the late answer.
It should at least work properly with the example file : https://github.com/fiware-cybercaptor/cybercaptor-data-extraction/releases/download/4.4.3/topology-generated.xml

Did you use Docker version ? 
`docker run --rm --name cybercaptor-server -p 8080:8080 fiwarecybercaptor/cybercaptor-server`
and
`docker run --rm --name cybercaptor-client -p 8888:80 fiware/cybercaptor-client`

CyberCAPTOR-Server can be debugged with the main log files presented in https://github.com/fiware-cybercaptor/cybercaptor-server#main-logs-files . 

It can be tested alone with API calls : https://github.com/fiware-cybercaptor/cybercaptor-server#api

For the client part, you can display the browser console to ensure that everything works as expected.

Which browser are you using ? Try with Chrome/Chromium.

**Comment by jhahkala** [comment]
Yes, I tried with the docker version, and uploading the example topology. All the graphs are empty. Also on the logs it prints:

2015/12/11 16:28:10 [error] 52#0: *2 open() "/home/app/cybercaptor-client/lib/angular/angular-cookies.js" failed (2: No such file or directory), client: 86.209.152.96, server: , request: "GET /lib/angular/angular-cookies.js HTTP/1.1", host: "our.host:8000", referrer: "http://our.host:8000/"

So, the angular-cookies.js is missing from the docker package. It seems to be also missing form the lib directory here in github. When I added that, and ran the code "python -m SimpleHTTPServer 8000", it still showed the empty graphs...

**Comment by fxaguessy** [comment]
I suppose, reading https://github.com/fiware-cybercaptor/cybercaptor-server/issues/10, that the server is working properly with curl calls, on the host that runs the browser ?

As far as I know, angular-cookies lib is not necessary for Cybercaptor-client. So, this might not be the problem.

Which browser are you using ? The initialize tab works as expected ?

**Comment by jhahkala** [comment]
Yes, the server works, or at least answers with something that looks like it could be proper answers to the example requests on the documentation.

If the angular-cookies lib is not necessary, it would be good to remove the calls for it from the pages, to avoid these error messages.

Tried with firefox and chrome.

The initialize page seems to work, can choose a file and upload and there is progress bar and the other tabs appear.

**Comment by jhahkala** [comment]
So, starting with virtual machine Ubuntu-14.4-x86_64-Server Minimal and three ssh consoles to it:
on the first I run:

> apt-get update
> apt-get upgrade
> apt-get install docker.io
> docker run --rm --name cybercaptor-server -p 8080:8080 fiwarecybercaptor/cybercaptor-server

on the second:
to test the server:

> curl http://localhost:8080/cybercaptor-server/rest/version/detailed
> curl -c /tmp/curl.cookie http://localhost:8080/cybercaptor-server/rest/json/initialize
> curl -b /tmp/curl.cookie http://localhost:8080/cybercaptor-server/rest/json/attack_path/number
> curl -b /tmp/curl.cookie http://localhost:8080/cybercaptor-server/rest/json/attack_path/0
> curl -b /tmp/curl.cookie http://localhost:8080/cybercaptor-server/rest/json/attack_graph
> curl -b /tmp/curl.cookie http://localhost:8080/cybercaptor-server/rest/json/attack_path/0/remediations
> curl -b /tmp/curl.cookie http://localhost:8080/cybercaptor-server/rest/json/topology
> these seem to produce valid answers.
> then start client:
> docker run --rm --name cybercaptor-client -p 8000:80 fiwarecybercaptor/cybercaptor-client

on third console open the firewall:
iptables -A INPUT -p tcp --dport 8000 -j ACCEPT

Then I connect to the client with chrome, upload the example dataSet.xml from the doc directory and selecting the configuration tab, the page looks like
![conf](https://cloud.githubusercontent.com/assets/1371631/11801221/22c298fa-a2e4-11e5-9b7d-72a33d6d0f61.png)

Same for all the other tabs, all the graphs are empty.

**Comment by jhahkala** [comment]
this picture was supposed to be in the previous comment

![conf](https://cloud.githubusercontent.com/assets/1371631/11801265/970769c0-a2e4-11e5-9a43-e12d5fecf5b7.png)

**Comment by fxaguessy** [comment]
Hello,

Perhaps you need to open also port 8080 for REST communication with cybercaptor-server:

`iptables -A INPUT -p tcp --dport 8080 -j ACCEPT` .

Did you try to access with your brower : http://your-vm-ip:8080/cybercaptor-server/rest/json/attack_path/number 

It should not work, but provide the error message `{"error":"The monitoring object is empty. Did you forget to initialize it ?"}`

**Comment by jhahkala** [comment]
Hi,

ok, so the browser talks to both the client and server.

Opened the port, but it was also necessary to change the configuration in the docker container, the urls in myApp.js to point to the right host.

Now it works!

Thanks!
